export const RECEIVE_MUSIC_VIDEOS = 'RECEIVE_MUSIC_VIDEOS'
export const RECEIVE_RECAP_VIDEOS = 'RECEIVE_RECAP_VIDEOS'
export const RECEIVE_DOC_VIDEOS = 'RECEIVE_DOC_VIDEOS'
export const RECEIVE_PROJ_VIDEOS = 'RECEIVE_PROJ_VIDEOS'

export const RECEIVE_FASHION_PHOTOS = 'RECEIVE_FASHION_PHOTOS'
export const RECEIVE_COM_PHOTOS = 'RECEIVE_COM_PHOTOS'
export const RECEIVE_PROJ_PHOTOS = 'RECEIVE_PROJ_PHOTOS'
export const RECEIVE_SHOWS_PHOTOS = 'RECEIVE_SHOWS_PHOTOS'
export const RECEIVE_PORT_PHOTOS = 'RECEIVE_PORT_PHOTOS'

export const RECEIVE_ALBUM_DESIGNS = 'RECEIVE_ALBUM_DESIGNS'
export const RECEIVE_BRANDS_DESIGNS = 'RECEIVE_BRANDS_DESIGNS'
export const RECEIVE_COM_DESIGNS = 'RECEIVE_COM_DESIGNS'
